# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xG0Bsz3l8egZGq0j9UHR-RsNgvqaDQlu
"""

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


import os
import csv



data = open("/kaggle/input/world-educational-data/Global_Education.csv", encoding = 'latin-1')
csvreader = csv.reader(data)
header = next(csvreader)
rows = []
for row in csvreader:
    rows.append(row)
data.close()
rows[155][0] = "Sao Tome and Principe" #did not parse well in the orginal data
rows[74][0] = "Guinea-Bissau" # '-' was read as '0'

country_data = {} #dictionary with the country name as key and the value being a list with the country data
countries = [] #list of all the countries and areas
for i in range(len(rows)):
    country_data[rows[i][0]] = rows[i][3:]
    countries.append(rows[i][0])

def pull_data_male(country):
    #shows all the male specific data for a country
    print("For the country " + country + " the following data is known:")
    print("out of school rate pre-primary age males: " + country_data[country][0]+"%")
    print("out of school rate primary age males: " + country_data[country][2]+"%")
    print("out of school rate lower secondary age males: " + country_data[country][4]+"%")
    print("out of school rate upper secondary age males: " + country_data[country][6]+"%")
    print("completion rate for primary education of males: " + country_data[country][8]+"%")
    print("completion rate for lower secondary education of males: " + country_data[country][10]+"%")
    print("completion rate for upper secondary education of males: " + country_data[country][12]+"%")
    print("literacy rate amoung males aged 15-24: " +country_data[country][20]+"%")
    print("*note that 0% can be the result of missing data \n")



def pull_data_female(country):
    #shows all the female specific data for a country
    print("For the country " + country + " the following data is known:")
    print("out of school rate pre-primary age females: " + country_data[country][1]+"%")
    print("out of school rate primary age females: " + country_data[country][3]+"%")
    print("out of school rate lower secondary age females: " + country_data[country][5]+"%")
    print("out of school rate upper secondary age females: " + country_data[country][7]+"%")
    print("completion rate for primary education of females: " + country_data[country][9]+"%")
    print("completion rate for lower secondary education of females: " + country_data[country][11]+"%")
    print("completion rate for upper secondary education of females: " + country_data[country][13]+"%")
    print("literacy rate amoung females aged 15-24: " +country_data[country][21]+"%")
    print("*note that 0% can be the result of missing data \n")

pull_data_male("Netherlands")
pull_data_female("Netherlands")

def compare_2(country_1, country_2, data_point):
    #returns the perentage difference between two countries at a given datapoint
    return(int(country_data[country_1][data_point]) - int(country_data[country_2][data_point]))


def ratefunction():
    #makes a list with values provided by the user on how important all the datapoints are
    rate = []
    r = 0;
    for x in range(0,22):
        print(header[x+3])
        #r = int(input("How important is this on a scale of 1-5"))
        if x < 8:
            rate.append(-1*r)
        else:
            rate.append(r)

    return(rate)

def compare(country_1, country_2):
    #compares two countries on wich one is better given the level of importance for the user
    som = 0
    rate = ratefunction()

    for x in range(0,22):
        som += rate[x] * compare_2(country_1, country_2, x)

    if som > 0:
        print(country_1+ " is better than "+ country_2 )
    elif som < 0:
        print(country_2+ " is better than "+ country_1)
    else:
        print("the two selected country are equal")

compare("Argentina", "Niger")